#!/bin/bash

echo ""
echo "Applying migration BusinessTradingName"

echo "Adding routes to conf/app.routes"

echo "" >> ../conf/app.routes
echo "GET        /businessTradingName                        controllers.BusinessTradingNameController.onPageLoad(mode: Mode = NormalMode)" >> ../conf/app.routes
echo "POST       /businessTradingName                        controllers.BusinessTradingNameController.onSubmit(mode: Mode = NormalMode)" >> ../conf/app.routes

echo "GET        /changeBusinessTradingName                  controllers.BusinessTradingNameController.onPageLoad(mode: Mode = CheckMode)" >> ../conf/app.routes
echo "POST       /changeBusinessTradingName                  controllers.BusinessTradingNameController.onSubmit(mode: Mode = CheckMode)" >> ../conf/app.routes

echo "Adding messages to conf.messages"
echo "" >> ../conf/messages.en
echo "businessTradingName.title = businessTradingName" >> ../conf/messages.en
echo "businessTradingName.heading = businessTradingName" >> ../conf/messages.en
echo "businessTradingName.name = name" >> ../conf/messages.en
echo "businessTradingName.name = name" >> ../conf/messages.en
echo "businessTradingName.checkYourAnswersLabel = businessTradingName" >> ../conf/messages.en
echo "businessTradingName.error.name.required = Enter name" >> ../conf/messages.en
echo "businessTradingName.error.name.required = Enter name" >> ../conf/messages.en
echo "businessTradingName.error.name.length = name must be 100 characters or less" >> ../conf/messages.en
echo "businessTradingName.error.name.length = name must be 100 characters or less" >> ../conf/messages.en

echo "Adding to UserAnswersEntryGenerators"
awk '/trait UserAnswersEntryGenerators/ {\
    print;\
    print "";\
    print "  implicit lazy val arbitraryBusinessTradingNameUserAnswersEntry: Arbitrary[(BusinessTradingNamePage.type, JsValue)] =";\
    print "    Arbitrary {";\
    print "      for {";\
    print "        page  <- arbitrary[BusinessTradingNamePage.type]";\
    print "        value <- arbitrary[BusinessTradingName].map(Json.toJson(_))";\
    print "      } yield (page, value)";\
    print "    }";\
    next }1' ../test/generators/UserAnswersEntryGenerators.scala > tmp && mv tmp ../test/generators/UserAnswersEntryGenerators.scala

echo "Adding to PageGenerators"
awk '/trait PageGenerators/ {\
    print;\
    print "";\
    print "  implicit lazy val arbitraryBusinessTradingNamePage: Arbitrary[BusinessTradingNamePage.type] =";\
    print "    Arbitrary(BusinessTradingNamePage)";\
    next }1' ../test/generators/PageGenerators.scala > tmp && mv tmp ../test/generators/PageGenerators.scala

echo "Adding to ModelGenerators"
awk '/trait ModelGenerators/ {\
    print;\
    print "";\
    print "  implicit lazy val arbitraryBusinessTradingName: Arbitrary[BusinessTradingName] =";\
    print "    Arbitrary {";\
    print "      for {";\
    print "        name <- arbitrary[String]";\
    print "        name <- arbitrary[String]";\
    print "      } yield BusinessTradingName(name, name)";\
    print "    }";\
    next }1' ../test/generators/ModelGenerators.scala > tmp && mv tmp ../test/generators/ModelGenerators.scala

echo "Adding to UserAnswersGenerator"
awk '/val generators/ {\
    print;\
    print "    arbitrary[(BusinessTradingNamePage.type, JsValue)] ::";\
    next }1' ../test/generators/UserAnswersGenerator.scala > tmp && mv tmp ../test/generators/UserAnswersGenerator.scala

echo "Adding helper method to CheckYourAnswersHelper"
awk '/class CheckYourAnswersHelper/ {\
     print;\
     print "";\
     print "  def businessTradingName: Option[Row] = userAnswers.get(BusinessTradingNamePage) map {";\
     print "    answer =>";\
     print "      Row(";\
     print "        key     = Key(msg\"businessTradingName.checkYourAnswersLabel\", classes = Seq(\"govuk-!-width-one-half\")),";\
     print "        value   = Value(lit\"${answer.name} ${answer.name}\"),";\
     print "        actions = List(";\
     print "          Action(";\
     print "            content            = msg\"site.edit\",";\
     print "            href               = routes.BusinessTradingNameController.onPageLoad(CheckMode).url,";\
     print "            visuallyHiddenText = Some(msg\"site.edit.hidden\".withArgs(msg\"businessTradingName.checkYourAnswersLabel\"))";\
     print "          )";\
     print "        )";\
     print "      )";\
     print "  }";\
     next }1' ../app/utils/CheckYourAnswersHelper.scala > tmp && mv tmp ../app/utils/CheckYourAnswersHelper.scala

echo "Migration BusinessTradingName completed"
