#!/bin/bash

echo ""
echo "Applying migration SomeInformationIsMissing"

echo "Adding routes to conf/app.routes"

echo "" >> ../conf/app.routes
echo "GET        /someInformationIsMissing                        controllers.SomeInformationIsMissingController.onPageLoad(mode: Mode = NormalMode)" >> ../conf/app.routes
echo "POST       /someInformationIsMissing                        controllers.SomeInformationIsMissingController.onSubmit(mode: Mode = NormalMode)" >> ../conf/app.routes

echo "GET        /changeSomeInformationIsMissing                  controllers.SomeInformationIsMissingController.onPageLoad(mode: Mode = CheckMode)" >> ../conf/app.routes
echo "POST       /changeSomeInformationIsMissing                  controllers.SomeInformationIsMissingController.onSubmit(mode: Mode = CheckMode)" >> ../conf/app.routes

echo "Adding messages to conf.messages"
echo "" >> ../conf/messages.en
echo "someInformationIsMissing.title = someInformationIsMissing" >> ../conf/messages.en
echo "someInformationIsMissing.heading = someInformationIsMissing" >> ../conf/messages.en
echo "someInformationIsMissing.checkYourAnswersLabel = someInformationIsMissing" >> ../conf/messages.en
echo "someInformationIsMissing.error.required = Enter someInformationIsMissing" >> ../conf/messages.en
echo "someInformationIsMissing.error.length = SomeInformationIsMissing must be 100 characters or less" >> ../conf/messages.en

echo "Adding to UserAnswersEntryGenerators"
awk '/trait UserAnswersEntryGenerators/ {\
    print;\
    print "";\
    print "  implicit lazy val arbitrarySomeInformationIsMissingUserAnswersEntry: Arbitrary[(SomeInformationIsMissingPage.type, JsValue)] =";\
    print "    Arbitrary {";\
    print "      for {";\
    print "        page  <- arbitrary[SomeInformationIsMissingPage.type]";\
    print "        value <- arbitrary[String].suchThat(_.nonEmpty).map(Json.toJson(_))";\
    print "      } yield (page, value)";\
    print "    }";\
    next }1' ../test/generators/UserAnswersEntryGenerators.scala > tmp && mv tmp ../test/generators/UserAnswersEntryGenerators.scala

echo "Adding to PageGenerators"
awk '/trait PageGenerators/ {\
    print;\
    print "";\
    print "  implicit lazy val arbitrarySomeInformationIsMissingPage: Arbitrary[SomeInformationIsMissingPage.type] =";\
    print "    Arbitrary(SomeInformationIsMissingPage)";\
    next }1' ../test/generators/PageGenerators.scala > tmp && mv tmp ../test/generators/PageGenerators.scala

echo "Adding to UserAnswersGenerator"
awk '/val generators/ {\
    print;\
    print "    arbitrary[(SomeInformationIsMissingPage.type, JsValue)] ::";\
    next }1' ../test/generators/UserAnswersGenerator.scala > tmp && mv tmp ../test/generators/UserAnswersGenerator.scala

echo "Adding helper method to CheckYourAnswersHelper"
awk '/class CheckYourAnswersHelper/ {\
     print;\
     print "";\
     print "  def someInformationIsMissing: Option[Row] = userAnswers.get(SomeInformationIsMissingPage) map {";\
     print "    answer =>";\
     print "      Row(";\
     print "        key     = Key(msg\"someInformationIsMissing.checkYourAnswersLabel\", classes = Seq(\"govuk-!-width-one-half\")),";\
     print "        value   = Value(lit\"$answer\"),";\
     print "        actions = List(";\
     print "          Action(";\
     print "            content            = msg\"site.edit\",";\
     print "            href               = routes.SomeInformationIsMissingController.onPageLoad(CheckMode).url,";\
     print "            visuallyHiddenText = Some(msg\"site.edit.hidden\".withArgs(msg\"someInformationIsMissing.checkYourAnswersLabel\"))";\
     print "          )";\
     print "        )";\
     print "      )";\
     print "  }";\
     next }1' ../app/utils/CheckYourAnswersHelper.scala > tmp && mv tmp ../app/utils/CheckYourAnswersHelper.scala

echo "Migration SomeInformationIsMissing completed"
